<?php

namespace Kiwi\Contao\DesignerBundle\DataContainer;

use Contao\FrontendTemplate;
use Contao\StringUtil;
use Contao\System;
use Contao\Automator;
use Contao\DataContainer;
use Kiwi\Contao\DesignerBundle\Models\ColorModel;
use Kiwi\Contao\DesignerBundle\Models\ColorSchemeModel;
use Kiwi\Contao\DesignerBundle\Util\ColorHelper;
use Symfony\Component\Filesystem\Filesystem;

class ColorListener
{
    public function updateScssFile(?DataContainer $objDca = null, ?int $undoId = null)
    {
        $strSuffix="";
        $targetPath = System::getContainer()->getParameter('kernel.project_dir') . '/files/themes/';
        $colorId = $objDca->id;

        // use undoId to distinguish ondelete_callback from onsubmit_callback
        if ($undoId) {
            // the record still exists at this point, so exclude its id
            $collColors = ColorModel::findBy(['NOT id = ?'], $colorId, ['return' => 'Collection']);
        } else {
            $collColors = ColorModel::findAll(['return' => 'Collection']);
        }

        if (!$collColors) {
            $collColors = [];
        }

        if($objDca->table == 'tl_page'){
            $arrColors =[];
            foreach($collColors as $objColor){
                if($strValue = $objDca->activeRecord->{"color_$objColor->variable"}){
                    $objColor->value = $strValue;
                    $arrColors[] = $objColor;
                }
            }

            $collColors = $arrColors;
            $strSuffix = "_$colorId";
            $targetPath = System::getContainer()->getParameter('kernel.project_dir') . '/files/pages/';
        }

        $fs = new Filesystem();
        $automator = new Automator();

        if (!$fs->exists($targetPath)) {
            $fs->mkdir($targetPath);
        }

        $strColorScss = ColorHelper::generateScssRules($collColors);

        file_put_contents($targetPath . "_colorvars{$strSuffix}.scss", "// This file is autogenerated. Do not change its contents, it will be overwritten.\n\n" . $strColorScss);

        $automator->purgeScriptCache();
    }

    public function labelCallback(array $row, string $label, DataContainer $objDca, array $labels): array
    {
        $color = ColorHelper::getCssColorFromValue($row['value']);

        return ['<div style="height:1em;width:1em;background-color:' . $color . '"></div>', $labels[1], '<span style="font-family:monospace">$' . $labels[2] . '</span>'];
    }

    public function valueSaveCallback(string $value, DataContainer $objDca): string
    {
        if(!$value) return $value;

        if (array_key_exists($value, ColorHelper::$arrHtmlColors)) {
            return ColorHelper::$arrHtmlColors[$value];
        }

        if (preg_match('/^#?([A-Fa-f\d]{3,4}|[A-Fa-f\d]{6}|[A-Fa-f\d]{8})$/', $value, $arrMatches)) {
            return '#' . $arrMatches[1];
        }

        if (mb_strpos($value, 'rgb') === 0 && $value[-1] === ')') {
            if ($value[3] == 'a' && $value[4] == '(') {
                $numbers = trim(mb_substr($value, 5, mb_strlen($value) - 1 - 5));
                $arrNumbers = explode(',', $numbers);
                if (count($arrNumbers) === 4) {
                    $err = false;
                    for ($i = 0; $i < 3; $i++) {
                        $intVal = intval(trim($arrNumbers[$i]));
                        if ((string)$intVal !== trim($arrNumbers[$i])) {
                            $err = true;
                        }
                        if ($intVal < 0 || $intVal > 255) {
                            $err = true;
                        }
                    }
                    $floatVal = floatval(trim($arrNumbers[3]));
                    if ((string)$floatVal !== trim($arrNumbers[3])) {
                        $err = true;
                    }
                    if ($err) {
                        throw new \Exception('bwuargh');
                    }
                    if ($floatVal < 0 || $floatVal > 1) {
                        $err = true;
                    }
                    if (!$err) {
                        return $value;
                    }
                }
            } elseif ($value[3] == '(') {
                $numbers = trim(mb_substr($value, 4, mb_strlen($value) - 1 - 4));
                $arrNumbers = explode(',', $numbers);
                if (count($arrNumbers) === 3) {
                    $err = false;
                    for ($i = 0; $i < 3; $i++) {
                        $intVal = intval(trim($arrNumbers[$i]));
                        if ((string)$intVal !== trim($arrNumbers[$i])) {
                            $err = true;
                        }
                        if ($intVal < 0 || $intVal > 255) {
                            $err = true;
                        }
                    }
                    if (!$err) {
                        return $value;
                    }
                }
            }
        }

        if (mb_strpos($value, 'hsl') === 0 && $value[-1] === ')') {
            if ($value[3] == 'a' && $value[4] == '(') {
                $numbers = trim(mb_substr($value, 5, mb_strlen($value) - 1 - 5));
                $arrNumbers = explode(',', $numbers);

                if (count($arrNumbers) === 4) {
                    $err = false;
                    for ($i = 0; $i < 3; $i++) {
                        $intVal = intval(trim($arrNumbers[$i]));
                        if ($i == 0 && ($intVal < 0 || $intVal > 360)) {
                            $err = true;
                        }
                        if (($i == 1 || $i == 2) && ($intVal < 0 || $intVal > 100)) {
                            $err = true;
                        }
                    }
                    $floatVal = floatval(trim($arrNumbers[3]));
                    if ((string)$floatVal !== trim($arrNumbers[3])) {
                        $err = true;
                    }
                    if ($err) {
                        throw new \Exception('bwuargh');
                    }
                    if ($floatVal < 0 || $floatVal > 1) {
                        $err = true;
                    }
                    if (!$err) {
                        return $value;
                    }
                }
            } elseif ($value[3] == '(') {
                $numbers = trim(mb_substr($value, 4, mb_strlen($value) - 1 - 4));
                $arrNumbers = explode(',', $numbers);

                if (count($arrNumbers) === 1) {
                    $arrNumbers = explode(' ', $numbers);
                }

                if (count($arrNumbers) === 3) {
                    $err = false;
                    for ($i = 0; $i < 3; $i++) {
                        $intVal = intval(trim($arrNumbers[$i]));
                        if ($i == 0 && ($intVal < 0 || $intVal > 360)) {
                            $err = true;
                        }
                        if ($i == 1 || $i == 2 && ($intVal < 0 || $intVal > 100)) {
                            $err = true;
                        }
                    }
                    if (!$err) {
                        return $value;
                    }
                }
            }
        }

        throw new \Exception('Invalid color value.');
    }

    public static function getCategoryOptions($varDca)
    {
        $arrOptions = [];

        $strTable = $varDca->table ?? $varDca['table'];
        $strField = $varDca->field ?? $varDca['field'];

        $objColorCollection = ColorModel::findAll();

        if ($objColorCollection && $strTable) {
            foreach ($objColorCollection as $objColor) {
                $arrCategories = StringUtil::deserialize($objColor->category);
                if (!($GLOBALS['TL_DCA'][$strTable]['fields'][$strField]['category'] ?? false) || $objColor->isApplicable && (!$arrCategories || in_array($GLOBALS['TL_DCA'][$strTable]['fields'][$strField]['category'], $arrCategories))) {
                    $arrOptions[$objColor->id] = $objColor->title;
                }
            }
        }

        return $arrOptions;
    }

    public function getIcons($objDca)
    {
        $arrOptions = [];

        $objColorCollection = ColorModel::findAll();

        if ($objColorCollection) {
            foreach ($objColorCollection as $objColor) {
                $arrOptions[$objColor->id] = "data:image/svg+xml," . rawurlencode(sprintf("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><rect width='16' height='16' fill='%s'/></svg>", $objColor->value));
            }
        }

        return $arrOptions;
    }
}
